Ensure content exists
If you follow the README instructions you will get this error
because the content directory is missing:

Error: Failed to serve the site
Error: Can't watch `content` for changes in folder `.../zola-vite-demo`. Does it exist, and do you have correct permissions?
Error: Reason: No path was found.
ERROR: "zola-serve" exited with 1.

This change ensures an empty content directory is present.